### ISSUE TITLE
Using `before_all` with `ActiveSupport::TestCase`

### ISSUE THREAD

**Issue by davidwessman** [test-prof/test-prof#214]
### Tell us about your environment

**Ruby Version:** 2.7.2

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rails 6.1.3

**TestProf Version:** 1.0.5

### What did you do?

Tried to use `before_all` with `ActiveSupport::TestCase`.

<details>
<summary>test_helper.rb</summary>

```ruby
ENV['RAILS_ENV'] ||= 'test'
require_relative "../config/environment"
require "rails/test_help"

require "test_prof/recipes/minitest/before_all"

class ActiveSupport::TestCase
  include TestProf::BeforeAll::Minitest
  # Run tests in parallel with specified workers
  parallelize(workers: :number_of_processors)

  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...

  before_all do
    @something = "WHAT"
  end
end
```

</details>

### What did you expect to happen?

Allow to run once before all tests.

### What actually happened?

```bash
Error:
BugTest#test_example:
NoMethodError: undefined method `activate!' for nil:NilClass
    .rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/test-prof-1.0.5/lib/test_prof/recipes/minitest/before_all.rb:83:in `before_setup'

Error:
BugTest#test_example:
NoMethodError: undefined method `each' for nil:NilClass
    .rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/test_fixtures.rb:167:in `teardown_fixtures'
    .rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/test_fixtures.rb:16:in `after_teardown'
    .rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/testing/setup_and_teardown.rb:51:in `after_teardown'
```

**Comment by palkan** [comment]
`before_all` in Minitest doesn't support inheritance; though, I think, we can add support for that
