### ISSUE TITLE
Flame graph doesn't play nice with create_default require line

### ISSUE THREAD

**Issue by awortham** [test-prof/test-prof#233]
### Tell us about your environment

**Ruby Version:**
 2.7.5

**Framework Version** 
Running Rails 6.0.4.4 and RSpec 3.10

**TestProf Version:**
1.0.7

### What did you do?
I ran flame graph on a spec. Originally I ran it on the entire suite, but this was overwhelming, so I ran it on a single spec and viewed the results. Then I added the changes `create_default` to the spec. (Love how it looks and I believe this is going to be a win for us). But I also wanted to measure the difference. So I renamed the original flame graph and re-ran the flame graph command.
FPROF=flamegraph bundle exec rspec spec/system/my_spec.rb:19

### What did you expect to happen?
I  expected to be able to compare results between the before and after for this single spec and see how much it flattened the graph.

### What actually happened?
```
An error occurred while loading ./spec/system/mar/administrations/user_can_edit_an_administration_spec.rb.
Failure/Error: require "test_prof/recipes/rspec/factory_default"

NoMethodError:
  private method `require' called for TestProf:Module
# ./spec/rails_helper.rb:17:in `require'
# ./spec/rails_helper.rb:17:in `<top (required)>'
# ./spec/system/mar/administrations/user_can_edit_an_administration_spec.rb:1:in `require'
# ./spec/system/mar/administrations/user_can_edit_an_administration_spec.rb:1:in `<top (required)>'
Run options: include {:locations=>{"./spec/system/mar/administrations/user_can_edit_an_administration_spec.rb"=>[19]}}
```
Now I can run specs and use `create_default`. However, something with the flame graph command doesn't understand requiring the `create_default` method. This results in a state where I can only use the flame graph without the `create_default` functionality. These two don't seem to play nice together. 

I would love to be able to compare before and after results with this graph.

**Comment by awortham** [comment]
I found a potential solution. Maybe this is already in the documentation somewhere and I just missed it, but I had to require test-prof prior to the line that I require the recipe.
```
require "test_prof" # This is required to be before the recipe line in order run the flame graph
require "test_prof/recipes/rspec/factory_default" # This is still required to use create_default
```
So - perhaps nothing is needed here, or maybe we could make an addition to the documentation somewhere?

Thanks so much for all your hard work on this gem. It's really eye-opening for me as I'm looking through our spec suite.

**Comment by palkan** [comment]
Oh, the private `#require` method from Kernel; interesting.

> perhaps nothing is needed here, or maybe we could make an addition to the documentation somewhere?

Yeah, all recipes use some shared code from the _core_ library (`test-prof`), so it's a unclear requirement. Updating the docs would be helpful for now (and for v2 we need to fix this).
