### ISSUE TITLE
(Rails 7.1 alpha) let_it_be can throw "SAVEPOINT active_record_1 does not exist"

### ISSUE THREAD

**Issue by jdelStrother** [test-prof/test-prof#265]
### Tell us about your environment

**Ruby Version:** 3.1.3

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** rspec 3.13.0pre, rspec-rails 6.1.0pre, rails 7.1.0.alpha

**TestProf Version:** 1.2.1

### What did you do?

Ran let_it_be without touching the database:

```ruby
RSpec.describe "test-prof test" do
  let_it_be(:foo) { 1 }

  specify { expect(1).to eq(1) }
end
```

### What did you expect to happen?

Spec passes

### What actually happened?

It raises `SAVEPOINT active_record_1 does not exist` in `after_teardown`:

<details><summary>Backtrace</summary>
```
# ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:742:in `query'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:742:in `block (2 levels) in raw_execute'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1011:in `block in with_raw_connection'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:983:in `with_raw_connection'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:740:in `block in raw_execute'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1121:in `log'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:739:in `raw_execute'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:772:in `internal_execute'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract/savepoints.rb:16:in `exec_rollback_to_savepoint'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:416:in `rollback_to_savepoint'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `rollback_to_savepoint'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:311:in `rollback'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:479:in `block in rollback_transaction'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:476:in `rollback_transaction'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:335:in `rollback_transaction'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/test_fixtures.rb:183:in `block in teardown_fixtures'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/test_fixtures.rb:182:in `each'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/test_fixtures.rb:182:in `teardown_fixtures'
     # ./vendor/cache/rails-ea7ac1594b4e/activerecord/lib/active_record/test_fixtures.rb:16:in `after_teardown'
     # ./vendor/cache/rails-ea7ac1594b4e/activesupport/lib/active_support/testing/time_helpers.rb:71:in `after_teardown'
     # ./vendor/cache/rspec-rails-0c54f938cb04/lib/rspec/rails/adapters.rb:76:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:352:in `call'
     # ./spec/rails_helper.rb:113:in `block (2 levels) in <top (required)>'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/sidekiq-7.0.8/lib/sidekiq/testing.rb:16:in `__set_test_mode'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/sidekiq-7.0.8/lib/sidekiq/testing.rb:30:in `fake!'
     # ./spec/support/sidekiq_helpers.rb:54:in `block (2 levels) in <main>'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/nix-bundle/ruby/3.1.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/hooks.rb:486:in `run'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example.rb:259:in `run'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example_group.rb:642:in `map'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example_group.rb:642:in `run_examples'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/example_group.rb:607:in `run'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/configuration.rb:2085:in `with_suite_hooks'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/cache/rspec-core-8caecca0b9b2/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/cache/rspec-core-8caecca0b9b2/exe/rspec:4:in `<top (required)>'
     # bin/rspec:5:in `load'
     # bin/rspec:5:in `<main>'
```
</details>

If `let_it_be` uses a database connection (eg `let_it_be(:foo) { User.first; 1 }`), it works fine.

Obviously Rails 7.1 is still alpha so I'm not expecting this to be a priority, but thought it was worth filing in case it saved someone some debugging time. (I'm also not sure if it's test-prof's fault or Rails - I can file the issue there if you think it's their bug?)

**Comment by palkan** [comment]
Thanks for the report! It's very helpful to catch future errors earlier 🙂

**Comment by palkan** [comment]
I tried to reproduce this problem here, but no luck: https://github.com/test-prof/test-prof/pull/268/files#diff-ccb81035ba717effd54cca0c7f36209662865600f5111fc9836c97d93d9ab297

Could you please confirm that you see this exception with the latest rails main?

**Comment by jdelStrother** [comment]
Bah, no luck reproducing it here either - wish I'd noted the exact git revisions in use, sorry. Happy to close this for now.

**Comment by palkan** [comment]
Thanks!

Let's close it for now and re-open if re-appears.
